/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/CircleHeadTwo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere006_1.geometry} material={materials.BodeOne} />
      <mesh geometry={nodes.Sphere006_2.geometry} material={materials.InnerBodyOne} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials['Glass.001']} scale={1.05} />
    </group>
  )
}

useGLTF.preload('/CircleHeadTwo.glb')
