/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ForWeb.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.RainyCloud.geometry} material={materials.Cloud} position={[0, -0.45, -0.06]} scale={0.53} />
    </group>
  )
}

useGLTF.preload('/ForWeb.glb')
