/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef , useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/RainyAnimation.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    console.log(actions);
    actions.ArmatureAction.play();
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="Bone001" position={[0, -1.05, -1.7]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="RainyRainDrop"
            geometry={nodes.RainyRainDrop.geometry}
            material={materials.Rain}
            position={[0, 0.41, -1.13]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.RainyCloud.geometry}
            material={materials.Cloud}
            position={[0, -0.45, -0.06]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.53}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/RainyAnimation.glb')
