/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef , useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Sunny.glb')

  useFrame(({clock})=>{
    group.current.rotation.y = clock.getElapsedTime();
  })

  useEffect(()=>{
    group.current.rotation.y = 90;
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.SunnyCloud.geometry} material={materials.Cloud} position={[0, -0.45, -0.06]} scale={0.53} />
      <mesh geometry={nodes.SunnySun.geometry} material={materials.Sun} position={[0, 1.3, 1.47]} scale={0.6} />
    </group>
  )
}